CREATE TABLE player_stats (
	playerId integer,
	playerName varchar(255),
    position varchar(255),
    year integer,
	week integer,
    season integer,
	totalPoints FLOAT,
	projectedPoints FLOAT,
    gamesPlayed FLOAT,
    passingAttempts FLOAT,
    passingCompletions FLOAT,
    passingIncompletions FLOAT,
    passingYards FLOAT,
    passingTouchdowns FLOAT,
    passing40PlusYardTD FLOAT,
    passing50PlusYardTD FLOAT,
    passing300To399YardGame FLOAT,
    passing400PlusYardGame FLOAT,
    passing2PtConversions FLOAT,
    passingInterceptions FLOAT,
    passingCompletionPercentage FLOAT,
    rushingAttempts FLOAT,
    rushingYards FLOAT,
    rushingTouchdowns FLOAT,
    rushing2PtConversions FLOAT,
    rushing40PlusYardTD FLOAT,
    rushing50PlusYardTD FLOAT,
    rushing100To199YardGame FLOAT,
    rushing200PlusYardGame FLOAT,
    rushingYardsPerAttempt FLOAT,
    receivingReceptions FLOAT,
    receivingYards FLOAT,
    receivingTouchdowns FLOAT,
    receiving2PtConversions FLOAT,
    receiving40PlusYardTD FLOAT,
    receiving50PlusYardTD FLOAT,
    receiving100To199YardGame FLOAT,
    receiving200PlusYardGame FLOAT,
    receivingTargets FLOAT,
    receivingYardsAfterCatch FLOAT,
    receivingYardsPerReception FLOAT,
    twoPtConversions FLOAT,
    fumbleRecoveredForTD FLOAT,
    passingTimesSacked FLOAT,
    fumbles FLOAT,
    lostFumbles FLOAT,
    turnovers FLOAT,
    madeFieldGoalsFrom50Plus FLOAT,
    attemptedFieldGoalsFrom50Plus FLOAT,
    missedFieldGoalsFrom50Plus FLOAT,
    madeFieldGoalsFrom40To49 FLOAT,
    attemptedFieldGoalsFrom40To49 FLOAT,
    missedFieldGoalsFrom40To49 FLOAT,
    madeFieldGoalsFromUnder40 FLOAT,
    attemptedFieldGoalsFromUnder40 FLOAT,
    missedFieldGoalsFromUnder40 FLOAT,
    madeFieldGoals FLOAT,
    attemptedFieldGoals FLOAT,
    missedFieldGoals FLOAT,
    madeExtraPoints FLOAT,
    attemptedExtraPoints FLOAT,
    missedExtraPoints FLOAT,
    defensive0PointsAllowed FLOAT,
    defensive1To6PointsAllowed FLOAT,
    defensive7To13PointsAllowed FLOAT,
    defensive14To17PointsAllowed FLOAT,
    defensiveBlockedKickForTouchdowns FLOAT,
    defensiveTouchdowns FLOAT,
    defensiveInterceptions FLOAT,
    defensiveFumbles FLOAT,
    defensiveBlockedKicks FLOAT,
    defensiveSafeties FLOAT,
    defensiveSacks FLOAT,
    kickoffReturnTouchdowns FLOAT,
    puntReturnTouchdowns FLOAT,
    interceptionReturnTouchdowns FLOAT,
    fumbleReturnTouchdowns FLOAT,
    defensivePlusSpecialTeamsTouchdowns FLOAT,
    defensiveForcedFumbles FLOAT,
    defensiveAssistedTackles FLOAT,
    defensiveSoloTackles FLOAT,
    defensiveTotalTackles FLOAT,
    defensivePassesDefensed FLOAT,
    kickoffReturnYards FLOAT,
    puntReturnYards FLOAT,
    puntsReturned FLOAT,
    defensivePointsAllowed FLOAT,
    defensive18To21PointsAllowed FLOAT,
    defensive22To27PointsAllowed FLOAT,
    defensive28To34PointsAllowed FLOAT,
    defensive35To45PointsAllowed FLOAT,
    defensive45PlusPointsAllowed FLOAT,
    defensiveYardsAllowed FLOAT,
    defensiveLessThan100YardsAllowed FLOAT,
    defensive100To199YardsAllowed FLOAT,
    defensive200To299YardsAllowed FLOAT,
    defensive300To349YardsAllowed FLOAT,
    defensive350To399YardsAllowed FLOAT,
    defensive400To449YardsAllowed FLOAT,
    defensive450To499YardsAllowed FLOAT,
    defensive500To549YardsAllowed FLOAT,
    defensive550PlusYardsAllowed FLOAT,
    netPunts FLOAT,
    puntYards FLOAT,
    puntsInsideThe10 FLOAT,
    puntsInsideThe20 FLOAT,
    blockedPunts FLOAT,
    puntTouchbacks FLOAT,
    puntFairCatches FLOAT,
    puntAverage FLOAT,
    puntAverage44_0 FLOAT,
    puntAverage42_0_43_9 FLOAT,
    puntAverage40_0_41_9 FLOAT,
    puntAverage38_0_39_9 FLOAT,
    puntAverage36_0_37_9 FLOAT,
    puntAverage34_0_35_9 FLOAT,
    puntAverage33_9AndUnder FLOAT,
    teamWin FLOAT,
    teamLoss FLOAT,
    teamTie FLOAT,
    pointsScored FLOAT,
    pointsMargin FLOAT,
    _25PlusPointWinMargin FLOAT,
    _20_24PointWinMargin FLOAT,
    _15_19PointWinMargin FLOAT,
    _10_14PointWinMargin FLOAT,
    _5_9PointWinMargin FLOAT,
    _1_4PointWinMargin FLOAT,
    _1_4PointLossMargin FLOAT,
    _5_9PointLossMargin FLOAT,
    _10_14PointLossMargin FLOAT,
    _15_19PointLossMargin FLOAT,
    _20_24PointLossMargin FLOAT,
    _25PlusPointLossMargin FLOAT,
    winPercentage FLOAT,
    madeFieldGoalsFrom60Plus FLOAT,
    attemptedFieldGoalsFrom60Plus FLOAT,
    missedFieldGoalsFrom60Plus FLOAT,
    defensive2PtReturns FLOAT
);

CREATE TABLE team_lineups(
    teamId integer,
    week integer,
    season integer,
    playerId integer,
    rosterPosition varchar(255),
    playerPosition varchar(10)
);

-- Activity table
CREATE TABLE Activity (
    ActivityId SERIAL PRIMARY KEY,
    ADateTime TIMESTAMP,
    AType VARCHAR(255),
    TeamId INT,
    PlayerId INT,
    FabCost INT
);

-- Team table
CREATE TABLE Teams (
    TeamId INT,
    TeamName VARCHAR(255),
    Owner VARCHAR(255)
);

-- GameDates table
CREATE TABLE GameDates (
    Year INT,
    Week INT,
    StartDate TIMESTAMP
);

-- Player table
CREATE TABLE Players (
    PlayerId INT,
    PlayerName VARCHAR(255),
    Position VARCHAR(255),
    proTeam VARCHAR(255)
);

CREATE TABLE Draft_data (
    year int,
    overallpick int,
    round int,
    pick int,
    playerId int,
    fantasyOwner int
);